# Generated by Django 5.1.4 on 2025-12-14 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_remove_record_content_remove_record_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='category',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='types',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='record',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='restaurant',
        ),
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.ratingstar', verbose_name='star'),
        ),
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='record',
            name='mainPhoto',
            field=models.ImageField(upload_to='education_main_photo/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='record',
            name='types',
            field=models.ManyToManyField(to='institutions.types', verbose_name='types'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.reviews', verbose_name='Parent'),
        ),
        migrations.CreateModel(
            name='EducationalInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('street', models.CharField(default='', max_length=200, verbose_name='Street')),
                ('mainPhoto', models.ImageField(upload_to='education_main_photo/', verbose_name='Photo')),
                ('description', models.TextField(verbose_name='Description')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Draft Field')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.category', verbose_name='category')),
                ('types', models.ManyToManyField(to='institutions.types', verbose_name='types')),
            ],
            options={
                'verbose_name': 'Education Institution',
                'verbose_name_plural': 'Education Institutions',
            },
        ),
        migrations.AddField(
            model_name='rating',
            name='EducationalInstitution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institutions.educationalinstitution', verbose_name='restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='EducationalInstitution',
            field=models.ForeignKey(default=1.0, on_delete=django.db.models.deletion.CASCADE, to='institutions.educationalinstitution', verbose_name='Educational Institution'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EducationalInstitutionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=120, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='education_photos/', verbose_name='Image')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.educationalinstitution', verbose_name='educational_institute')),
            ],
            options={
                'verbose_name': 'Institution Photo',
                'verbose_name_plural': 'Institution Photos',
            },
        ),
        migrations.DeleteModel(
            name='RestaurantPhoto',
        ),
        migrations.DeleteModel(
            name='Restaurants',
        ),
    ]
